In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import os
pasta_drive = '/content/drive/My Drive/DadosAntaq/'
if os.path.exists(pasta_drive):
    arquivos = os.listdir(pasta_drive)
    print(f"Arquivos encontrados em 'DadosAntaq': {arquivos}")
else:
    print(f"A pasta 'DadosAntaq' não foi encontrada no Google Drive.")

Mounted at /content/drive
Arquivos encontrados em 'DadosAntaq': ['2024', '2025', 'Modelo Antaq.png', 'Instalacao_Destino.csv', 'Instalacao_Origem.csv', 'ParAtracCar_2024.csv', 'ParAtracCar_2025.csv']

In [3]:
arquivo1 = '/content/drive/My Drive/DadosAntaq/ParAtracCar_2024.csv'
arquivo2 = '/content/drive/My Drive/DadosAntaq/ParAtracCar_2025.csv'
arquivo3 = '/content/drive/My Drive/DadosAntaq/Instalacao_Origem.csv'
arquivo4 = '/content/drive/My Drive/DadosAntaq/Instalacao_Destino.csv'

In [4]:
PAC2024 = pd.read_csv(arquivo1, sep=';', encoding='utf-8', low_memory=False)
PAC2025 = pd.read_csv(arquivo2, sep=';', encoding='utf-8', low_memory=False)
Insta_Orig = pd.read_csv(arquivo3, sep=';', encoding='utf-8', low_memory=False)
Insta_Dest = pd.read_csv(arquivo4, sep=';', encoding='utf-8', low_memory=False)

In [5]:
Insta_Orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3557 entries, 0 to 3556
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Origem                      3556 non-null   object
 1   Origem Nome                 3533 non-null   object
 2   CDBigramaOrigem             3554 non-null   object
 3   CDTrigramaOrigem            3313 non-null   object
 4   CDTUPOrigem                 243 non-null    object
 5   Rio Origem                  3557 non-null   object
 6   Região Hidrográfica Origem  3549 non-null   object
 7   UF.Origem                   3557 non-null   object
 8   Cidade Origem               3557 non-null   object
 9   País Origem                 3557 non-null   object
 10  Continente Origem           3557 non-null   object
 11  BlocoEconomico_Origem       1350 non-null   object
dtypes: object(12)
memory usage: 333.6+ KB

In [6]:
Insta_Orig.head(10)

,Origem,Origem Nome,CDBigramaOrigem,CDTrigramaOrigem,CDTUPOrigem,Rio Origem,Região Hidrográfica Origem,UF.Origem,Cidade Origem,País Origem,Continente Origem,BlocoEconomico_Origem
0,USPBG,Pittsburg,US,PBG,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
1,GBLGW,London-Gatwick Apt,GB,LGW,NaN,Não se aplica,Não se aplica,Não se aplica,-,Reino Unido da Grã Bretanha e Irlanda,EUROPA,União Européia
2,DEWVN,Wilhelmshaven,DE,WVN,NaN,Não se aplica,Não se aplica,Não se aplica,-,ALEMANHA,EUROPA,União Européia
3,PACHG,Chiriqui Grande,PA,CHG,NaN,Não se aplica,Não se aplica,Não se aplica,-,PANAMÁ,AMÉRICA CENTRAL,NaN
4,INIXM,Madurai,IN,IXM,NaN,Não se aplica,Não se aplica,Não se aplica,-,INDIA,ÁSIA,NaN
5,PAPAP,Canal do Panamá,PA,PAP,NaN,Não se aplica,Não se aplica,Não se aplica,-,PANAMÁ,AMÉRICA CENTRAL,NaN
6,SARAB,Rabigh,SA,RAB,NaN,Não se aplica,Não se aplica,Não se aplica,-,ARÁBIA SAUDITA,ÁSIA,NaN
7,USSSI,Brunswick,US,SSI,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
8,GBLGB,Long Hanborough,GB,LGB,NaN,Não se aplica,Não se aplica,Não se aplica,-,Reino Unido da Grã Bretanha e Irlanda,EUROPA,União Européia
9,JPFUK,Fukuoka,JP,FUK,NaN,Não se aplica,Não se aplica,Não se aplica,-,JAPÃO,ÁSIA,NaN

In [7]:
colunas_necessarias = [
    'Origem',
    'Origem Nome',
    'UF.Origem',
    'País Origem',
    'Continente Origem'
]

Insta_Orig = Insta_Orig[colunas_necessarias].copy()

In [8]:
for col in colunas_necessarias:
    Insta_Orig[col] = (
        Insta_Orig[col]
        .astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )
Insta_Orig['Origem'] = Insta_Orig['Origem'].astype(str)

In [9]:
Insta_Orig = Insta_Orig.drop_duplicates(subset='Origem')

In [10]:
Insta_Dest = pd.read_csv(arquivo4, sep=';', encoding='utf-8', low_memory=False)

In [16]:
Insta_Dest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5273 entries, 0 to 5272
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Destino                      5272 non-null   object
 1   Nome Destino                 5238 non-null   object
 2   CDBigramaDestino             5270 non-null   object
 3   CDTrigramaDestino            4994 non-null   object
 4   CDTUPDestino                 278 non-null    object
 5   Rio Destino                  5273 non-null   object
 6   Região Hidrográfica Destino  5260 non-null   object
 7   UF.Destino                   5272 non-null   object
 8   Cidade Destino               5273 non-null   object
 9   País Destino                 5273 non-null   object
 10  Continente Destino           5273 non-null   object
 11  BlocoEconomico_Destino       1971 non-null   object
dtypes: object(12)
memory usage: 494.5+ KB

In [17]:
Insta_Dest.head(10)

,Destino,Nome Destino,CDBigramaDestino,CDTrigramaDestino,CDTUPDestino,Rio Destino,Região Hidrográfica Destino,UF.Destino,Cidade Destino,País Destino,Continente Destino,BlocoEconomico_Destino
0,USAKE,Ankeny,US,AKE,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
1,USWHC,West Have,US,WHC,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
2,USAVD,Avondale,US,AVD,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
3,DEKLT,Kaiserslautern,DE,KLT,NaN,Não se aplica,Não se aplica,Não se aplica,-,ALEMANHA,EUROPA,União Européia
4,USBUK,Burbank,US,BUK,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
5,USSCK,Stockton,US,SCK,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
6,USBYO,Burnsville,US,BYO,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
7,USABQ,Albuquerque,US,ABQ,NaN,Não se aplica,Não se aplica,Não se aplica,-,ESTADOS UNIDOS,AMÉRICA DO NORTE,NaN
8,NOTOS,Tromso,NO,TOS,NaN,Não se aplica,Não se aplica,Não se aplica,-,NORUEGA,EUROPA,NaN
9,ITADN,Aldino,IT,ADN,NaN,Não se aplica,Não se aplica,Não se aplica,-,ITÁLIA,EUROPA,União Européia

In [20]:
colunas_necessarias = [
    'Destino',
    'Nome Destino',
    'UF.Destino',
    'País Destino',
    'Continente Destino'
]

Insta_Dest = Insta_Dest[colunas_necessarias].copy()

In [24]:
for col in colunas_necessarias:
    Insta_Dest[col] = (
        Insta_Dest[col]
        .astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )
Insta_Dest['Destino'] = Insta_Dest['Destino'].astype(str)

In [27]:
Insta_Dest = Insta_Dest.drop_duplicates(subset='Destino')

In [29]:
Insta_Orig.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3545 entries, 0 to 3556
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Origem             3545 non-null   object
 1   Origem Nome        3545 non-null   object
 2   UF.Origem          3545 non-null   object
 3   País Origem        3545 non-null   object
 4   Continente Origem  3545 non-null   object
dtypes: object(5)
memory usage: 166.2+ KB

In [72]:
PAC2024 = pd.read_csv(arquivo1, sep=';', encoding='utf-8', low_memory=False)
PAC2025 = pd.read_csv(arquivo2, sep=';', encoding='utf-8', low_memory=False)

In [73]:
PAC2024_2025 = pd.concat([PAC2024, PAC2025], ignore_index=True)

In [74]:
PAC2024_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453116 entries, 0 to 453115
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   IDTemposDescontos             453116 non-null  int64
 1   IDAtracacao                   453116 non-null  int64
 2   DescricaoTempoDesconto        453116 non-null  object
 3   DTInicio                      453116 non-null  object
 4   DTTermino                     453116 non-null  object
 5   duracao                       453116 non-null  object
 6   duracao_horas                 453116 non-null  float64
 7   Porto Atracação               453116 non-null  object
 8   Complexo Portuário            453116 non-null  object
 9   UF                            453116 non-null  object
 10  Região Geográfica             453116 non-null  object
 11  Data Atracação                453116 non-null  object
 12  Data Chegada                  453116 non-null  object
 13  Data Desatracação             453116 non-null  object
 14  Origem                        442536 non-null  object
 15  Destino                       442536 non-null  object
 16  Tipo Operação da Carga        452680 non-null  object
 17  Carga Geral Acondicionamento  199628 non-null  object
 18  Tipo Navegação                452680 non-null  object
 19  ano                           453116 non-null  int64
 20  mes                           453116 non-null  object
dtypes: float64(1), int64(3), object(17)
memory usage: 72.6+ MB

In [75]:
PAC2024_2025["Origem"] = PAC2024_2025["Origem"].str.upper()
PAC2024_2025["Destino"] = PAC2024_2025["Destino"].str.upper()

In [76]:
Insta_Orig["Origem"] = Insta_Orig["Origem"].str.upper()
Insta_Dest["Destino"] = Insta_Dest["Destino"].str.upper()

In [77]:
PAC2024_2025["Origem"] = PAC2024_2025["Origem"].str.strip()
PAC2024_2025["Destino"] = PAC2024_2025["Destino"].str.strip()

In [78]:
Insta_Orig = Insta_Orig.drop_duplicates("Origem")
Insta_Dest = Insta_Dest.drop_duplicates("Destino")

In [79]:
PAC2024_2025 = PAC2024_2025.merge(Insta_Orig, on="Origem", how="left")

In [80]:
PAC2024_2025 = PAC2024_2025.merge(Insta_Dest, on="Destino", how="left")

In [84]:
PAC2024_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453116 entries, 0 to 453115
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   IDTemposDescontos             453116 non-null  int64
 1   IDAtracacao                   453116 non-null  int64
 2   DescricaoTempoDesconto        453116 non-null  object
 3   DTInicio                      453116 non-null  object
 4   DTTermino                     453116 non-null  object
 5   duracao                       453116 non-null  object
 6   duracao_horas                 453116 non-null  float64
 7   Porto Atracação               453116 non-null  object
 8   Complexo Portuário            453116 non-null  object
 9   UF                            453116 non-null  object
 10  Região Geográfica             453116 non-null  object
 11  Data Atracação                453116 non-null  object
 12  Data Chegada                  453116 non-null  object
 13  Data Desatracação             453116 non-null  object
 14  Origem                        442536 non-null  object
 15  Destino                       442536 non-null  object
 16  Tipo Operação da Carga        452680 non-null  object
 17  Carga Geral Acondicionamento  453116 non-null  object
 18  Tipo Navegação                452680 non-null  object
 19  ano                           453116 non-null  int64
 20  mes                           453116 non-null  object
 21  Origem Nome                   442536 non-null  object
 22  UF.Origem                     442536 non-null  object
 23  País Origem                   442536 non-null  object
 24  Continente Origem             442536 non-null  object
 25  Nome Destino                  442536 non-null  object
 26  UF.Destino                    442536 non-null  object
 27  País Destino                  442536 non-null  object
 28  Continente Destino            442536 non-null  object
dtypes: float64(1), int64(3), object(25)
memory usage: 100.3+ MB

In [82]:
PAC2024_2025["Origem Nome"].isna().sum()
PAC2024_2025["Nome Destino"].isna().sum()

np.int64(10580)

In [83]:
PAC2024_2025["Carga Geral Acondicionamento"] = (
    PAC2024_2025["Carga Geral Acondicionamento"]
    .fillna("Não informado")
)

In [86]:
PAC2024_2025.to_csv("PAC2024_2025.csv", index=False, sep=';', encoding='utf-8')

In [87]:
from google.colab import drive
drive.mount('/content/drive')

PAC2024_2025.to_csv("/content/drive/MyDrive/DadosAntaq/PAC2024_2025.csv", index=False, sep=';', encoding='utf-8')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).